"""empty message

Revision ID: 5ee6074d5614
Revises: 
Create Date: 2022-05-18 10:39:04.676537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee6074d5614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_img',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('post', 'post_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'post_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'user_img',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
