"""empty message

Revision ID: ffa71f2b766d
Revises: 5ee6074d5614
Create Date: 2022-05-18 13:20:05.538960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa71f2b766d'
down_revision = '5ee6074d5614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
